apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fd34fb-prod
resources:
- ../../base
images:
- name: artifacts.developer.gov.bc.ca/kfd3-fd34fb-local/backend-services
  newTag: main-latest
commonLabels:
  env: prod
patches:
- target:
    kind: ImageStream
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: fd34fb-tools

